### PR TITLE
fix qualified name get bug

### PR DESCRIPTION
**Pull request by wiyr**
## Summary
resolves https://github.com/Instagram/LibCST/issues/656
## Test Plan
 python -m unittest libcst.metadata.tests.test_scope_provider.ScopeProviderTest.test_get_qualified_names_for_the_same_prefix

### CODE REVIEW

**Comment by stroxler** [comment]
Thanks for the fix @wiyr!

This looks good to me, but it would be clearer if it shipped with a new unit test that would have failed on the old code. Do you have time to add that?

**Comment by stroxler** [comment]
FYI the CI failures are not related - they are due to a click/black version mismatch and I'm working on a fix

**Comment by wiyr** [comment]
added one simple unittest

**Review by stroxler — APPROVED** [review]
Awesome, thanks for the fix!

**Pull request merged**
