### PR TITLE
Fix pyre command for type inference provider

### PR DESCRIPTION
**Pull request by rodrigozhou**
## Summary

Pyre command for type inference provider has one of its params quoted and causing the Pyre to fail to parse the command line.

## Test Plan

Added unit test to generate the cache and compare with the expected result.

### CODE REVIEW

**Comment by zsol** [comment]
Looks like the new test is failing because `pyre` is not started. Might need to wrap the test code in a context manager or decorator that runs `pyre start --no-watchman` and tears it down afterwards (`pyre stop`)

**Comment by zsol** [comment]
cc @stroxler if the quotes are causing a problem, how are you not running into it?

**Comment by rodrigozhou** [comment]
@zsol Updated to start and stop Pyre in test setUp and tearDown functions.

**Comment by stroxler** [comment]
My changes bumped the pyre version which did seem to trigger a pyre start somewhere because I had to add the `--no-watchman` flag, but it sounds like we probably didn't start pyre pointed at the test code (my guess is that we were starting it up pointed at LibCST itself)

The error we're getting makes me think we lack a `.pyre_configuration` json file in the test fixture.

Assuming I'm correct about this being the problem, we could fix that by manually adding one, or probably (according to https://pyre-check.org/docs/getting-started#setting-up-a-project) by running `pyre init` prior to `pyre start`.

**Review by zsol — APPROVED** [review]
lets go

**Pull request merged**
