### PR TITLE
Add FlattenSentinel

### LINKED ISSUE #263: Inserting statements into blocks
I need to refactor code in a way that inserts statements into blocks. For example, let's say I want to extract a constant as a variable. That is, go from:

```python
y = 1 + 2
```

Into:

```python
x1 = 1
x2 = 2
y = x1 + x2
```

Using the standard AST library, I can express this as follows using NodeTransformers:

```python
import ast
import astor

class FindNumbers(ast.NodeTransformer):
    def __init__(self):
        self.assgns = []
        self.i = 0
        
    def fresh(self):
        self.i += 1
        return f'x{self.i}'
        
    def visit_Num(self, node):
        var = self.fresh()
        self.assgns.append(ast.Assign(targets=[ast.Name(id=var)], value=node))
        return ast.Name(id=var)

class ExtractNumbers(ast.NodeTransformer):
    def visit_Assign(self, assgn):
        finder = FindNumbers()
        finder.visit(assgn)
        return finder.assgns + [assgn]
    
stmt = ast.parse('y = 1 + 2')
print(astor.to_source(ExtractNumbers().visit(stmt)))
```

One key element of this is that NodeTransformers can return a list of statements, which enables the code above to insert the additional assignments during `visit_Assign`. The relevant code in CPython is here: https://github.com/python/cpython/blob/3.8/Lib/ast.py#L439-L440

As far as I can tell, this is not possible in LibCST. The transformer `leave` methods must return a `CSTNode`, and there are no nodes which can represent a block of statements that aren't indented.

Is there another way to accomplish this task in LibCST? If not, would y'all be open to a PR to add this feature?

### PR DESCRIPTION
**Pull request by cdonovick**
## Summary
Adds a `FlattenSentinel` as proposed by @sk- in #269 to resolve #263.

The main idea is to allow transformers to return multiple statements to replace a single statement.

## Test Plan
Wrote basic tests to ensure both `BaseSmallStatement` and `BaseStatement`  could be replaced with a `FlattenSentinel`. 

## Notes
Does not currently type check but I want to make sure this design is acceptable before I try to push `FlattenSentinel` basically everywhere.

### CODE REVIEW

**Comment by cdonovick** [comment]
Another possible option which might make typing a bit more sane would be to add types:
```Python3
class SmallStatementSeq(BaseSmallStatement):
    nodes: Sequence[BaseSmallStatement]

class StatementSeq(BaseStatement):
    nodes: Sequence[BaseStatement]   
```

These types would simply exist to allow transformers to return multiple nodes instead of a single node.

**Comment by cdonovick** [comment]
I think the `*Seq` types approach is in some ways not as nice as they would continue to live in the AST until they were serialized, but the two approach could be potentially combined with something like:

```Python3
class _FlattenSentinel:
    nodes: Sequence[CSTNode]

class SmallStatementSeq(BaseSmallStatement, _FlattenSentinel):
    nodes: Sequence[BaseSmallStatement]

class StatementSeq(BaseStatement, _FlattenSentinel):
    nodes: Sequence[BaseStatement]
```
And have the transformer machinery flatten eagerly.

**Comment by jimmylai** [comment]
FlattenSentinel can solve the case of replacing a node (e.g. a statement) with multiple nodes. We still need other helpers to make other use case easier, e.g. moving/adding statements to an another location, and that can be another PR.

FlattenSentinel idea looks good to me. @cdonovick please go ahead to complete this PR by fixing the type error and add detailed document in
https://github.com/Instagram/LibCST/blob/6731aa5d2940ce82dd221963b64a496955bfd07a/docs/source/visitors.rst

**Comment by cdonovick** [comment]
Probably won't get the docs done today but I will try to get them done tomorrow.

**Comment by cdonovick** [comment]
@jimmylai should be all set when you have a chance to review.

**Comment by cdonovick** [comment]
@jimmylai Any chance this can be merged?

**Review by jimmylai — APPROVED** [review]
Sorry for the late review. The change looks great!

**Pull request merged**
